### ISSUE TITLE
Voicemail Notifications and Visual Voicemail Appear Broken (Visible Wireless)

### ISSUE THREAD

**Issue by ilikenwf** [GrapheneOS/os-issue-tracker#1629]
I suspect this may be APN related as my phone displays itself as using Verizon, not Visible, and while Visible is VZW owned, they still have their own APN settings the last I checked.

This issue occurs on both my Pixel 5A as well as my parents' Pixel 4XLs.

**Comment by ilikenwf** [comment]
Perhaps not APN related as my settings are correct.

**Comment by akc3n** [comment]
@ilikenwf have you had a chance to read https://grapheneos.org/usage#carrier-functionality
> We would suggest using Google Dialer with sandboxed Google Play if you are unable to get this feature working.

Furthermore, https://github.com/GrapheneOS/os-issue-tracker/issues/1108

And here is the official google support for pixels with documentation mentioning ["Visible—Verizon"
](https://support.google.com/phoneapp/answer/2811844?hl=en#zippy=%2Cview-voicemails-as-a-list-in-your-phone-app%2Cview-a-transcript-of-your-voicemails) under the transcript menu.

Additionally, it may perhaps even help to read their [turn on visual voicemail](https://support.google.com/phoneapp/answer/2811844#visual_voicemail_supported) Incase there is something useful there for your case.

**Comment by ilikenwf** [comment]
This isn't specific to visual voicemail. While I can certainly call voicemail, I'm not even receiving notifications of having new voicemail messages, nor are my parents.

My Pixel 5A has the voicemail tab in the dialer, and while I used to receive the notifications and also had working visual voicemail, I no longer do.

My phone has no google services installed, my parents use the sandboxed layer.

In the case of my parents' Pixel 4XL's, they don't even have a voicemail tab displayed, neither on the stock dialer nor the google dialer.

Short of some kind of carrier/dialer config the only other thing I can think of trying is attempting to have Visible reprovision our accounts for voicemail and visual voicemail.

**Comment by ilikenwf** [comment]
@akc3n in addition, I'm running version 2022102800 - so either the fix isn't in the beta builds, or I'm lacking something...

**Comment by thestinger** [comment]
Reset your network settings. APNs get locked into the initial provisioned settings so you don't get updates to APNs.

**Comment by thestinger** [comment]
If that doesn't work, please post the carrier settings string show in the cellular settings menu. It appears you're being given the wrong APN and carrier configuration but I expect a network settings reset will fix it. GrapheneOS substantially improved this over the past year or so but you would have still had the old APN settings from before we implemented better conversion of the stock Pixel APN database if you installed before we made the improvements. That's just how this works in Android, perhaps to avoid breaking things for users with things already set up.

**Comment by ilikenwf** [comment]
That does not appear to have worked, sadly...

Interestingly the sim shows up as "Verizon" but the APN properly points to Visible - VSBLINTERNET for the APN config. Calls & SMS also says "Verizon."

Carrier settings string is visible_us-40000004454.44

**Comment by ilikenwf** [comment]
After going through the process of reprovisioning and troubleshooting with Visible, this issue is not resolved. In fact, after force resetting the phone application and clearing cache/storage, the visual voicemail options are totally gone.

I suspect this is a config issue or regression as I put the sim in my GrapheneOS Pixel 3A running build SP2A.220505.0082022090700 and visual voicemail properly setup and started working.

**Comment by derzahla** [comment]
I can confirm.  Just migrated from a pixel3 with VVM working perfectly and have been trying to figure out why it doesnt even show up on my new  pixel 5

**Comment by ilikenwf** [comment]
Yeah this seems to be a widespread issue across multiple pixels.

**Comment by ilikenwf** [comment]
@thestinger I'd have to check again, but the aforementioned 3A on SP2A.220505.0082022090700 if I recall doesn't any longer work with VVM after the latest update.

Regression somewhere?

I have a Pixel 6A on the way, there's a swap deal where I'm basically just paying the tax for black Friday, and I like the idea of longer support...I'll test on it before/after as well.

**Comment by ilikenwf** [comment]
Ok, so using the stock OS on my new Pixel 6A, visual voicemail setup and worked properly (Android 12). After installing GrapheneOS, unfortunately, it still does not.

I think we must be missing some kind of configuration somewhere. @thestinger  - sorry to keep tagging you here. I'm not up to date on my knowledge of how these configurations operate anymore, or else I'd try to be more helpful than just reporting the issue.

**Comment by ilikenwf** [comment]
This could also be a regression of some kind...but Googling Android 13 and visual voicemail indicates it is a bug and Google is blaming carriers.

**Comment by ilikenwf** [comment]
On my 6A, I managed to get it working but I don't particularly want to do it this way - I had to install the Google Services and Google Dialer, and after changing the voicemail phone number and triggering setup by removing and reinstalling the SIM, I eventually got it activated under the google dialer.

Why is it that this worked fine in GrapheneOS based on AOSP 12, yet it happens to be that in 13, one must resort to using Google's proprietary spyware to make it work?

**Comment by ilikenwf** [comment]
I think this points toward a potential issue in https://github.com/GrapheneOS/platform_packages_apps_Dialer - maybe not the VVM and carrier configs, but some kind of issue. I know that the Google dialer experienced VVM woes when Android 13 betas were released, and so that may provide some clue?

**Comment by pewterrock** [comment]
I just discovered this same issue with Visible on my Pixel 4a. I just don't get many voicemails and I did not notice the issue until now, but it appears to have popped up around the same time. @ilikenwf have you had much progress on resolving your issue?

**Comment by ilikenwf** [comment]
@pewterrock the only solve so far has sadly been to install google dialer and the sandboxed play services, set the dialer to default (I tend to disable sensors, but the rest of the perms are needed), then I change the voicemail number to my full number instead of *86 - IE +1XXXXXXXXXX - if after a bit voicemail does not setup, you can probably toggle it off and on again in the dialer settings or clear the dialer storage and then open it again...

I'm still thinking carrier config issue or some kind of android version detection if there is some as my old android 12 install on my 3A worked fine with the stock dialer until after upgrade.

**Comment by ilikenwf** [comment]
> @ilikenwf have you had a chance to read https://grapheneos.org/usage#carrier-functionality
> 
> > We would suggest using Google Dialer with sandboxed Google Play if you are unable to get this feature working.
> 
> Furthermore, #1108
> 
> And here is the official google support for pixels with documentation mentioning ["Visible—Verizon" ](https://support.google.com/phoneapp/answer/2811844?hl=en#zippy=%2Cview-voicemails-as-a-list-in-your-phone-app%2Cview-a-transcript-of-your-voicemails) under the transcript menu.
> 
> Additionally, it may perhaps even help to read their [turn on visual voicemail](https://support.google.com/phoneapp/answer/2811844#visual_voicemail_supported) Incase there is something useful there for your case.

While I realize this could be the case I have trouble believing it because the Android 12 build of GrapheneOS worked with the stock dialer on my 3A until after upgrade...

**Comment by derzahla** [comment]
> While I realize this could be the case I have trouble believing it because the Android 12 build of GrapheneOS worked with the stock dialer on my 3A until after upgrade...

I mean, if I go to settings->voicemail->advanced settings in the dialer app, it shows "Service: Your carrier", which I'm pretty sure was set to my actual carrier name back when it worked.  Seems carrier is not defined in current voicemail config
![image](https://user-images.githubusercontent.com/46491701/210108922-2e550fd9-9cc5-43d8-ba13-91739a1a6ab8.png)

**Comment by CheddarAnon** [comment]
> > While I realize this could be the case I have trouble believing it because the Android 12 build of GrapheneOS worked with the stock dialer on my 3A until after upgrade...
> 
> I mean, if I go to settings->voicemail->advanced settings in the dialer app, it shows "Service: Your carrier", which I'm pretty sure was set to my actual carrier name back when it worked. Seems carrier is not defined in current voicemail config ![image](https://user-images.githubusercontent.com/46491701/210108922-2e550fd9-9cc5-43d8-ba13-91739a1a6ab8.png)

I am experiencing the same issue with the same display as derzahla. Pixel 7 Pro on Verizon esim and physical sim.

**Comment by theuser18** [comment]
I am experiencing the same issue on Pixel 7 on T-Mobile. Below are my carrier settings and APN info. Does it look normal?

Carrier Settings: tmobile_us-42000000023.10

APN: fast.tmobile.com

![Screenshot_20230109-164358](https://user-images.githubusercontent.com/77016379/211423415-a7b51675-61f4-4bc7-9af0-c1c8cac5a1e6.png)

**Comment by qcasey** [comment]
I was having this same issue with Verizon on the Google Dialer. I turned off Visual Voicemail then turned it back on, then rebooted my device. Still the same problem.

I check maybe 5 days later and the dialer asks me to set up VV, and now it's working correctly. 🤷 

Settings > Voicemail > Advanced still shows "Your carrier" instead of Verizon, that may be unrelated to this bug.

**Comment by jerry-best** [comment]
I had this problem as well. Visual voicemail didn't show up for me on Visible with the stock dialer, and I never did try the Google Dialer.

Visible has been rolling out new plans which have different APNs and network config, and I just wanted to report that this issue resolved itself when I upgraded to the new Visible plan.

**Comment by ilikenwf** [comment]
They recently gave me an offer to keep the same price but move over to their new network. This for me has also fixed visual voicemail with the built in dialer, allowing me to remove the Google dialer.

I am closing the issue.
