### ISSUE TITLE
Wifi calling not working on Pixel 7

### ISSUE THREAD

**Issue by gitubinator** [GrapheneOS/os-issue-tracker#1648]
Wifi calling worked perfectly on my Pixel 6. Upgraded to a Pixel 7 using the same sim & network and Wifi calling would not work. After many calls with support with my carrier (Telstra in Australia), trying a new sim card and eventually re-flashing GrapheneOS once the Pixel 7 came out of experimental, I still had no luck getting Wifi calling to work. I just flashed back to stock android and wifi calling worked straight away! And then re-flashed to Graphene, and no love. So it seems like it is an issue with GrapheneOS on the Pixel 7.

**Comment by ZsZolee** [comment]
The same problem on my side too. No VoLTE and VoWIFI on my Pixel 7 Pro.

**Comment by McMarius11** [comment]
i sadly have the same issue using Telekom Germany here

**Comment by NikoBellicIV** [comment]
I am having this issue on a Pixel 4a. Apologies for posting in a Pixel 7 thread but this seems like the same issue.
I've tried Xfinity (Verizon MVNO) and AT&T prepaid.  In both cases I activated and tested Wi-Fi calling in stock Android but after flashing Graphene and enabling Wi-Fi Calling it won't work.
In phone's testing menu "WiFi Calling Provisioned" is flipped to ON but in IMS Status "Voice over WiFi" reported as "Unavailable".
"Use WiFi Calling" option in Settings->Network & internet -> Calls & SMS is turned ON
Enabling Airplane mode, enabling wifi, and attempting a call produces the error "Turn off airplane mode or connect to a wireless network to make a call."

**Comment by esntngv** [comment]
I suffer from this problem as well, it is definitely a GrapheneOS issue as it works fine on stock Android.
I have a Pixel 7 Pro and use a German SIM from Telekom.

**Comment by gitubinator** [comment]
Thanks heaps for looking into this @empratyush, mush appreciated!

**Comment by gitubinator** [comment]
Understood. Multiple commenters here and over at the forums have stated that Wi-Fi calling either works on stock Android and not on graphene or worked on graphene on a previous pixel model but now no longer works after upgrading to Pixel 7. I'm in both camps. Wi-Fi calling worked perfectly on a Pixel 6 running Graphene, moved the same sim to a Pixel 7 running graphene and it didn't work. Installed stock Android and Wi-Fi calling is working, installed latest version of grapheneOS and Wi-Fi calling no longer works. Really appreciate you looking into this, fairly certain it's a bug with graphene and Pixel 7.

**Comment by gitubinator** [comment]
I actually posed the question over at the forums if anybody running a Pixel 7 has Wi-Fi calling and nobody has confirmed that they have.

**Comment by esntngv** [comment]
@empratyush 

Are there any findings about this problem yet?

**Comment by empratyush** [comment]
Not yet.

**Comment by gitubinator** [comment]
> 

A few people including myself have tested installing stock android on Pixel 7/7 Pro and had Wifi Calling working, then tried GrapheneOS on the same device with same sim & network and confirmed it no longer works, so definitely an issue with GrapheneOS on Pixel 7/7 Pro

**Comment by swagglepuf** [comment]
Can confirm that Wi-Fi calling is not working on my pixel 7 pro using T-Mobile network. Phone info confirms the device is provisioned for Wi-Fi calling. Called T-Mobile and they confirmed everything on their end is also setup correctly. The device was purchased unlocked from google as well.  

I can also confirm that Wi-Fi calling works perfectly when using the stock pixel software as well. I know the information states that Graphene should seamlessly work with Wi-Fi calling if supported on stock software. 

I hope there is a resolution for this because I have to have Wi-Fi calling in some of the locations I go for work. That's the only way I am able to text and call.

**Comment by jsrlabs** [comment]
I can confirm Wi-Fi Calling is not working on my Pixel 7 Pro on the AT&T (US) network. Wi-Fi calling works when I was on  stock Android, but after flashing GrapheneOS onto the same phone, it does not work. In the phone's testing menu "WiFi Calling Provisioned" is ON, but in IMS Status "Voice over WiFi" reported as "Unavailable".

**Comment by esntngv** [comment]
@thestinger 
Do you know anything about this serious problem yet, there must be some explanation that this occurs specifically only with GrapheneOS...?

**Comment by thestinger** [comment]
Please don't unnecessarily ping me. Contributors able to replicate this issue are welcome to work on it.

**Comment by alci63** [comment]
I can confirm the problem: 
Pixel 7 pro, Bouygues Telecom, FRA
Works fine with stock ROM, doesn't with grapheneos.
WiFi calling option is present and checked, but WiFi calling does not work.
Also *#*#4636#*#* shows phone information, and IMS state says vowifi and volte are unavailable (but IMS is registered)

**Comment by alci63** [comment]
Found this doc, might be relevant, but I am far far from being an expert.... https://source.android.com/docs/core/connect/ims-service-entitlement

**Comment by ASerbinski** [comment]
@thestinger (addressed to you because you closed the thread) I'm not sure that this is really all fixed.

Pixel 7 Pro running on 2022120700, Freedom Mobile (Canada). We had the sim card upgraded a couple of days ago specifically to enable VoLTE and VoWIFI.

When the card is put in my Pixel 6 Pro, VoWIFI is working. Back in the Pixel 7 Pro and it exhibits the same problem as described in this issue; Wifi Calling Provisioned (ON), IMS Status/Voice over Wifi: Unavailable.

Phone has been rebooted to no effect.

**Comment by flawedworld** [comment]
Unrelated to this issue. You should make sure your carrier supports the Pixel 7 explicitly with Wi-Fi calling.

**Comment by ASerbinski** [comment]
It actually is related to this issue, and the device is explicitly supported by and SOLD BY the carrier; https://shop.freedommobile.ca/en-CA/devices/Google/Pixel-7-Pro?sku=810029937337&planSku=Promo%20Big%20Gig%20Unlimited%20%2B%20Talk%2021GB&deviceOption=TradeUp

**Comment by flawedworld** [comment]
It's not. This issue was resolved by configuring the QualifiedNetworkService properly in the OS. This is now a new issue.

**Comment by ASerbinski** [comment]
Apparently not. Have considered the possibility that the patch only worked for a subset of the problem? There is no reason there can't be more than one problem causing an issue.

**Comment by flawedworld** [comment]
No, it's resolved. You have a different issue to this.

**Comment by ASerbinski** [comment]
No, its only been resolved for some. The issue remains for others.

**Comment by gitubinator** [comment]
@flawedworld have you tried flashing stock OS and seeing if wifi calling works? If so then it is a grapheneOS issue. The recent fix works for me.

**Comment by swagglepuf** [comment]
The phone is listed as wifi calling compatible. The question is did you setup wifi calling prior to flashing Graphene on the device. According to freedom mobile you have to manually setup the 911 address and activate wifi calling. Which I don't think is possible in Graphene, but is possible on stock. 

Wifi calling is fixed on my 7 pro with the patch as well as many others.

**Comment by somehuman60** [comment]
I have Pixel 6a and neither WoWiFi nor VoLTE is working. On other phone with stock OS is working fine. I'm on Sunrise in Switzerland and they support WoWiFi and VoLTE for all sim cards.

**Comment by swagglepuf** [comment]
> I have Pixel 6a and neither WoWiFi nor VoLTE is working. On other phone with stock OS is working fine. I'm on Sunrise in Switzerland and they support WoWiFi and VoLTE for all sim cards.

It doesn't look like the pixel is even available to buy in Switzerland. You can't even buy it through your mobile provider. This isn't a Graphene problem this is a carrier doesn't support it problem. Sunrise doesn't officially have the pixel available through them. You could call them and be like hey I need to you white list my phone to get these features working.

**Comment by somehuman60** [comment]
> It doesn't look like the pixel is even available to buy in Switzerland. You can't even buy it through your mobile provider. This isn't a Graphene problem this is a carrier doesn't support it problem. Sunrise doesn't officially have the pixel available through them. You could call them and be like hey I need to you white list my phone to get these features working.<

This is partially true, because Pixel phones are available in Switzerland through biggest Online Store Digitec. Digitec is virtual mobile provider on Sunrise Network and all phones sold through Digitec are whitelisted by Sunrise. I own Oneplus 9 Pro which isn't officially sold in Switzerland too, but because Digitec sold it, Sunrise whitelisted it (5G, WoWiFi, VoLTE works fine), and not only Oneplus but many other brands officially not sold in Switzerland are whitelisted by Sunrise. 

In the phone's testing menu "WiFi Calling Provisioned" is ON, and in IMS Status "Voice over WiFi" reported as "Available", but "VoLTE" is reported as "Unavailable".

**Comment by swagglepuf** [comment]
> > It doesn't look like the pixel is even available to buy in Switzerland. You can't even buy it through your mobile provider. This isn't a Graphene problem this is a carrier doesn't support it problem. Sunrise doesn't officially have the pixel available through them. You could call them and be like hey I need to you white list my phone to get these features working.<
> 
> This is partially true, because Pixel phones are available in Switzerland through biggest Online Store Digitec. Digitec is virtual mobile provider on Sunrise Network and all phones sold through Digitec are whitelisted by Sunrise. I own Oneplus 9 Pro which isn't officially sold in Switzerland too, but because Digitec sold it, Sunrise whitelisted it (5G, WoWiFi, VoLTE works fine), and not only Oneplus but many other brands officially not sold in Switzerland are whitelisted by Sunrise.
> 
> In the phone's testing menu "WiFi Calling Provisioned" is ON, and in IMS Status "Voice over WiFi" reported as "Available", but "VoLTE" is reported as "Unavailable".

That's fine an all, but sunrise is not an officially supported carrier by google. There is no guarantee that all the features will work, and this is outlined in usage guide provided by GrapheneOS 

 https://grapheneos.org/usage#carrier-functionality

**Comment by somehuman60** [comment]
> That's fine an all, but sunrise is not an officially supported carrier by google. There is no guarantee that all > the features will work, and this is outlined in usage guide provided by GrapheneOS
> 
> https://grapheneos.org/usage#carrier-functionality

Probably I wasn't clear, it is definitely a GrapheneOS issue as WiFi Calling/VoLTE works fine on stock Android and Sunrise Network, although Sunrise is not an officially supported carrier by Google.

**Comment by 8473795** [comment]
Is there any update/plan/eta on this?

I can confirm the bug exists - wifi calling and volte not working on Pixel 7 pro GrapheneOS.

Volte option is missing altogether from the settings, even though the carrier clearly supports it and it works on stock os.

Wifi calling option exists in the settings, is turned on, however wifi calling is not working (no wifi calling symbol in status bar).

I tried with 4g only and other modes.

In regards to volte, I expect to see this option on the settings:

![7061222-f-0dd5d70a-0f9d-4329-8553-746181dedbb1](https://user-images.githubusercontent.com/120998037/208340524-cbd5553f-b005-4160-b4cc-f0921d33ad02.png)

This is what I am seeing (no volte option):

![Screenshot_20221219-140629_1](https://user-images.githubusercontent.com/120998037/208340607-5a41b3a9-697f-437f-851c-b114a40a9b43.png)

**Comment by thestinger** [comment]
There are currently no reproducible issues with VoLTE or VoWi-Fi on 7th generation Pixels. No one is working on it. You're wrong about a toggle being available there for all carriers with the feature. Only some carriers have the toggle. You aren't showing a screenshot from the stock Pixel OS on the same device. Comparing to another device / carrier is not helpful.

**Comment by thestinger** [comment]
The issue that this issue report was created about was resolved. The person who filed the issue confirmed that the issue was resolved. Everything here about other carriers, etc. is off topic for this issue report since it has been confirmed that the person who filed it no longer has an issue. Anything else is a different issue. Locking this thread due to continued off topic discussion. Also, if you want to file a new issue please confirm that the feature is supported on the stock OS on the same device model first.
