### ISSUE TITLE
Missing APN Endpoints in Owner Profile

### ISSUE THREAD

**Issue by NarwhalPrince** [GrapheneOS/os-issue-tracker#4559]
#### Description
Under **Access Point Names**, the APN endpoints do not appear, and instead, the message "Access Point Name settings are not available for this user" is displayed. This issue occurs within the **owner profile**.

#### Device Details
- **Device:** Pixel 7 Pro  
- **OS Version:** GrapheneOS 2024121200  
- **Carrier:** Google Fi (eSIM)  

#### Additional Information
I am willing to provide any logs or further information necessary to assist in troubleshooting this issue. Please let me know the specific logs or steps required.

**Comment by teodorzl** [comment]
Additional information - it appears that after installing an eSIM profile, mobile data does not work. When VoLTE is enabled, calls do not work, except when using VoWiFi. Disabling VoLTE fixes calls.

Once APN settings are reset to default, all the aforementioned issues are resolved and I am now able to access APN settings

**Comment by NarwhalPrince** [comment]
Resetting APN settings does not resolve the issue of the endpoints being missing for me.

**Comment by brentcklein** [comment]
Was experiencing this same issue on a fresh install on a Pixel 8 Pro with Google Fi carrier. Following [these instructions](https://shkspr.mobi/blog/2024/03/solved-access-point-name-settings-are-not-available-for-this-user/) using the APN details from [this site](https://www.apnsettings.org/usa/google-fi-apn/) resolved the issue for me (though obviously you'll need to find or obtain the correct APN details for your carrier if you don't use Google Fi.)

1. "Access Point Name settings are not available for this user" is misleading. It just means there isn't an APN for that SIM.
2. Add an APN for your carrier. Go to Settings > Network & Internet > SIMs > {your carrier name} > Access Point Names and tap the plus (+) icon to add a new APN. I used the details linked above for Google Fi, but these details can be obtained from your carrier if you can't find or do not trust details found online.
3. Make sure to save the new APN and activate it.
4. You should now see 5G or LTE on the status bar next to your signal strength. Disconnect from WiFi, make sure mobile data is activated under Settings > Network & Internet > SIMs, and verify you have data.
