### ISSUE TITLE
Unable to type via scrcpy while phone at lock screen

### ISSUE THREAD

**Issue by cemysce** [GrapheneOS/os-issue-tracker#4616]
I just updated my Pixel 8 Pro to the latest GOS version (build 2024123000), and now can no longer type remotely to my phone over adb+scrcpy while the phone is at the lock screen.  It was always the case that the screen capture would be blocked while at the lock screen, which made remote typing my PIN all the more important because I'd have no way of seeing what I was clicking on.  Now it seems no keyboard input is being accepted at all.  This makes it incredibly tedious and time consuming to develop for and interact with a phone while not in proximity of it.

**Comment by cemysce** [comment]
I had been using `scrcpy` 2.4, but I just updated to 3.1 and have the same issue.

**Comment by cemysce** [comment]
I've also confirmed that typing over `scrcpy` works elsewhere.  Just not at the lock screen anymore.

**Comment by cemysce** [comment]
Interesting, didn't know about that option, nor the recommendation from `scrcpy` devs to use UHID if regularly using `scrcpy`.  I'll try it and report back.  Thanks!

**Comment by cemysce** [comment]
`-K` doesn't help.  The `scrcpy` help text implies I need to setup the physical keyboard layout on the phone first or `-K` will have no effect.  It tells me to go to "Settings -> System -> Languages and input -> Physical keyboard", which doesn't quite exist in my Android/GrapheneOS version so I navigated instead to "Settings -> System -> Keyboard", but there were no settings for a physical keyboard.  The help text also suggests activating the relevant intent via ADB with `adb shell am start -a android.settings.HARD_KEYBOARD_SETTINGS`, which briefly flashes something on the phone's screen but it goes away immediately.

I am using ADB over Wi-Fi.  Closer reading of the `-K` option's help text shows that `--otg` is also required, and that option only makes sense if using ADB over USB, which I am not.  Indeed if I run with that option, I get an error about not finding the device over USB.

**Comment by rom1v** [comment]
> The `scrcpy` help text implies I need to setup the physical keyboard layout on the phone first or `-K` will have no effect.

You need to setup the physical keyboard to configure the keyboard layout. If you don't do that, you may not have the layout you're expecting, but it still works.

> It tells me to go to "Settings -> System -> Languages and input -> Physical keyboard", which doesn't quite exist

Note that it exists only when a physical keyboard is enabled (either a physical keyboard is plugged, or scrcpy is running with `-K`).

> Closer reading of the `-K` option's help text shows that `--otg` is also required

No, without OTG it enables UHID keyboard.

> and that option only makes sense if using ADB over USB, which I am not.

Only AOA requires USB, not UHID.

**Comment by WaleedMortaja** [comment]
I did not know you can type the PIN at the lock screen, good info. However, I would like to inform you that the communication with the phone is not encrypted when using `scrcpy` so it is not safe to send PIN or Password if you are using WI-FI.

**Comment by cemysce** [comment]
> Note that it exists only when a physical keyboard is enabled (either a physical keyboard is plugged, or scrcpy is running with `-K`).

Confirmed.  Thanks!  But even after setting a layout (there already seemed to be one selected anyway), unlocking the lock screen doesn't work.

> Only AOA requires USB, not UHID.

Yeah, the `scrcpy` help text was explicit about AOA requiring USB, but regarding `-K` in general seems to be phrased in a way that implies it all requires USB.  That and I guess when I looked for the Physical Keyboard settings I must've gone back to running without `-K` so I missed it.  Anyway, thanks!

> the communication with the phone is not encrypted when using scrcpy so it is not safe to send PIN or Password if you are using WI-FI

Fair point, but I am using this over an encrypted Wi-Fi that I only use at home from my PC, never elsewhere, so that mitigates the risk sufficiently for me.  Indeed you're right, it seems `adb` isn't encrypted at all.

**Comment by WaleedMortaja** [comment]
I have `scrcpy 3.1` I use the `-K` option. I can use my laptop keyboard to type in the lock screen, so the issue seems to have been fixed.

> I am using this over an encrypted Wi-Fi that I only use at home from my PC, never elsewhere, so that mitigates the risk sufficiently for me. Indeed you're right, it seems adb isn't encrypted at all.

If there other people that connect to the same home network, they can capture the non-encrypted `adb` communication. It is up to you to balance between your convenience and security and to decide if that risk is acceptable for your situation.

I have found a way to bypass the screen lock. I do not know if it is a feature or a security bug:
After you unlock the phone (profile) manually for once, you can use the `scrcpy --new-display` option when connecting to the phone to create a new virtual display instead of mirroring the phone screen. The new display does NOT ask for the PIN.

**Comment by cemysce** [comment]
> I have `scrcpy 3.1` I use the `-K` option. I can use my laptop keyboard to type in the lock screen, so the issue seems to have been fixed.

What version of GrapheneOS are you using?  I tried again after the most recent update (build 2025010700) and it still wasn't working for me.

**Comment by WaleedMortaja** [comment]
> What version of GrapheneOS are you using? I tried again after the most recent update (build 2025010700) and it still wasn't working for me. And I am also using scrcpy with -K.

I re-tried today and it is still working for me. I was able to fully unlock the screen. I has not been using PIN scramble (I forgot to test that, but last time it was enabled, and I could write, but I did not try to enter the correct PIN to check). I use the same GhrapheneOS as yours `2025010700`, I use Arch Linux and I had installed `scrcpy 3.1-1` from default repository. I do not think I had made any special config except for connecting to the phone over its own hotspot by using a workaround which is me connecting a USB cable between the phone and the laptop then running the command `adb tcpip <port>`(only once per phone reboot), then I connect to the phone using `scrcpy --tcpip=_gateway:<port> -K` (Connecting to the phone over its own hotspot does not usually work because `adb over Wi-Fi` wants Wi-Fi connection and does not consider its own hotspot to be acceptable unfortunately, that is why I use this work around. The `_gateway` gets replaced by the gateway IP which in my case is the IP of the phone. You can replace that by manually entering the IP of the phone)

**Comment by cemysce** [comment]
> I has not been using PIN scramble

I tried disabling that and it doesn't fix it for me.  I also tried disabling the enhanced security option (thus re-enabling the lock screen animations), and that also didn't fix it for me.  So I'm not sure why it's working for you, but the earlier posts from thestinger imply the devs have confirmed the problem, so hopefully they have identified the cause.

**Comment by empratyush** [comment]
I am able to reproduce this on stock os as well.

**Comment by empratyush** [comment]
It is just bug. If you try swipe action (using mouse or touchscreen) instead of 'SPACE' button on keyboard. It will work fine.
